//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dynamic_reconfigure_pkg package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dynamic_reconfigure_pkg__DART_SIMULATOR_GUICONFIG_H__
#define __dynamic_reconfigure_pkg__DART_SIMULATOR_GUICONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic_reconfigure_pkg
{
  class dart_simulator_guiConfigStatics;

  class dart_simulator_guiConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(dart_simulator_guiConfig &config, const dart_simulator_guiConfig &max, const dart_simulator_guiConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const dart_simulator_guiConfig &config1, const dart_simulator_guiConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, dart_simulator_guiConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const dart_simulator_guiConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dart_simulator_guiConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const dart_simulator_guiConfig &config) const = 0;
      virtual void getValue(const dart_simulator_guiConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T dart_simulator_guiConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T dart_simulator_guiConfig::* field;

      virtual void clamp(dart_simulator_guiConfig &config, const dart_simulator_guiConfig &max, const dart_simulator_guiConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const dart_simulator_guiConfig &config1, const dart_simulator_guiConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, dart_simulator_guiConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const dart_simulator_guiConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dart_simulator_guiConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const dart_simulator_guiConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const dart_simulator_guiConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, dart_simulator_guiConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, dart_simulator_guiConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<dart_simulator_guiConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(dart_simulator_guiConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("reset_state"==(*_i)->name){reset_state = boost::any_cast<bool>(val);}
        if("reset_state_x"==(*_i)->name){reset_state_x = boost::any_cast<double>(val);}
        if("reset_state_y"==(*_i)->name){reset_state_y = boost::any_cast<double>(val);}
        if("reset_state_theta"==(*_i)->name){reset_state_theta = boost::any_cast<double>(val);}
        if("reset_vehicle_number"==(*_i)->name){reset_vehicle_number = boost::any_cast<int>(val);}
        if("dynamic_model_choice"==(*_i)->name){dynamic_model_choice = boost::any_cast<int>(val);}
      }
    }

    bool reset_state;
double reset_state_x;
double reset_state_y;
double reset_state_theta;
int reset_vehicle_number;
int dynamic_model_choice;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool reset_state;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double reset_state_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double reset_state_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double reset_state_theta;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int reset_vehicle_number;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int dynamic_model_choice;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("dart_simulator_guiConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const dart_simulator_guiConfig &__max__ = __getMax__();
      const dart_simulator_guiConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const dart_simulator_guiConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const dart_simulator_guiConfig &__getDefault__();
    static const dart_simulator_guiConfig &__getMax__();
    static const dart_simulator_guiConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const dart_simulator_guiConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void dart_simulator_guiConfig::ParamDescription<std::string>::clamp(dart_simulator_guiConfig &config, const dart_simulator_guiConfig &max, const dart_simulator_guiConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class dart_simulator_guiConfigStatics
  {
    friend class dart_simulator_guiConfig;

    dart_simulator_guiConfigStatics()
    {
dart_simulator_guiConfig::GroupDescription<dart_simulator_guiConfig::DEFAULT, dart_simulator_guiConfig> Default("Default", "", 0, 0, true, &dart_simulator_guiConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reset_state = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reset_state = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reset_state = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<bool>("reset_state", "bool", 0, "A Boolean parameter to reset the state", "", &dart_simulator_guiConfig::reset_state)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<bool>("reset_state", "bool", 0, "A Boolean parameter to reset the state", "", &dart_simulator_guiConfig::reset_state)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reset_state_x = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reset_state_x = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reset_state_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<double>("reset_state_x", "double", 0, "X position to reset to", "", &dart_simulator_guiConfig::reset_state_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<double>("reset_state_x", "double", 0, "X position to reset to", "", &dart_simulator_guiConfig::reset_state_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reset_state_y = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reset_state_y = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reset_state_y = 0.8;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<double>("reset_state_y", "double", 0, "Y position to reset to", "", &dart_simulator_guiConfig::reset_state_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<double>("reset_state_y", "double", 0, "Y position to reset to", "", &dart_simulator_guiConfig::reset_state_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reset_state_theta = -3.15;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reset_state_theta = 3.15;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reset_state_theta = 3.15;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<double>("reset_state_theta", "double", 0, "Orientation to reset to in radians", "", &dart_simulator_guiConfig::reset_state_theta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<double>("reset_state_theta", "double", 0, "Orientation to reset to in radians", "", &dart_simulator_guiConfig::reset_state_theta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reset_vehicle_number = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reset_vehicle_number = 4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reset_vehicle_number = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<int>("reset_vehicle_number", "int", 0, "Select which vehicle to reset position", "{'enum': [{'name': 'vehicle', 'type': 'int', 'value': 1, 'srcline': 16, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '1', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'vehicle', 'type': 'int', 'value': 2, 'srcline': 17, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '2', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'vehicle', 'type': 'int', 'value': 3, 'srcline': 18, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '3', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'vehicle', 'type': 'int', 'value': 4, 'srcline': 19, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '4', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set wich vehicle to reset position'}", &dart_simulator_guiConfig::reset_vehicle_number)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<int>("reset_vehicle_number", "int", 0, "Select which vehicle to reset position", "{'enum': [{'name': 'vehicle', 'type': 'int', 'value': 1, 'srcline': 16, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '1', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'vehicle', 'type': 'int', 'value': 2, 'srcline': 17, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '2', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'vehicle', 'type': 'int', 'value': 3, 'srcline': 18, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '3', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'vehicle', 'type': 'int', 'value': 4, 'srcline': 19, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': '4', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set wich vehicle to reset position'}", &dart_simulator_guiConfig::reset_vehicle_number)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dynamic_model_choice = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dynamic_model_choice = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dynamic_model_choice = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<int>("dynamic_model_choice", "int", 0, "Model choice which is edited via an enum", "{'enum': [{'name': 'Kinematic_bicycle', 'type': 'int', 'value': 1, 'srcline': 27, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': 'sets the dynamic model to kinematic bicycle', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Dynamic_bicycle', 'type': 'int', 'value': 2, 'srcline': 28, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': 'sets the dynamic model to dynamic bycicle with linear tire forces', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set dynamic model'}", &dart_simulator_guiConfig::dynamic_model_choice)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dart_simulator_guiConfig::AbstractParamDescriptionConstPtr(new dart_simulator_guiConfig::ParamDescription<int>("dynamic_model_choice", "int", 0, "Model choice which is edited via an enum", "{'enum': [{'name': 'Kinematic_bicycle', 'type': 'int', 'value': 1, 'srcline': 27, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': 'sets the dynamic model to kinematic bicycle', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Dynamic_bicycle', 'type': 'int', 'value': 2, 'srcline': 28, 'srcfile': '/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg', 'description': 'sets the dynamic model to dynamic bycicle with linear tire forces', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set dynamic model'}", &dart_simulator_guiConfig::dynamic_model_choice)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(dart_simulator_guiConfig::AbstractGroupDescriptionConstPtr(new dart_simulator_guiConfig::GroupDescription<dart_simulator_guiConfig::DEFAULT, dart_simulator_guiConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<dart_simulator_guiConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<dart_simulator_guiConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<dart_simulator_guiConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    dart_simulator_guiConfig __max__;
    dart_simulator_guiConfig __min__;
    dart_simulator_guiConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const dart_simulator_guiConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static dart_simulator_guiConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &dart_simulator_guiConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const dart_simulator_guiConfig &dart_simulator_guiConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const dart_simulator_guiConfig &dart_simulator_guiConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const dart_simulator_guiConfig &dart_simulator_guiConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<dart_simulator_guiConfig::AbstractParamDescriptionConstPtr> &dart_simulator_guiConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<dart_simulator_guiConfig::AbstractGroupDescriptionConstPtr> &dart_simulator_guiConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const dart_simulator_guiConfigStatics *dart_simulator_guiConfig::__get_statics__()
  {
    const static dart_simulator_guiConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = dart_simulator_guiConfigStatics::get_instance();

    return statics;
  }

//#line 16 "/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg"
      const int dart_simulator_gui_vehicle = 1;
//#line 17 "/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg"
      const int dart_simulator_gui_vehicle = 2;
//#line 18 "/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg"
      const int dart_simulator_gui_vehicle = 3;
//#line 19 "/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg"
      const int dart_simulator_gui_vehicle = 4;
//#line 27 "/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg"
      const int dart_simulator_gui_Kinematic_bicycle = 1;
//#line 28 "/home/lorenzo/OneDrive/PhD/Code/DART/catkin_ws/src/dynamic_reconfigure_pkg/cfg/dart_simulator_gui.cfg"
      const int dart_simulator_gui_Dynamic_bicycle = 2;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DART_SIMULATOR_GUIRECONFIGURATOR_H__
