min_particles: 50
max_particles:             500
kld_err:                   0.01
kld_z:                     0.99
update_min_d:              0.10
update_min_a:              0.10
resample_interval:         2
transform_tolerance:       0.5
recovery_alpha_slow:       0.00
recovery_alpha_fast:       0.00
# --- initial pose ---
#Vikon lab
#initial_pose_x:            2.7
#initial_pose_y:            -0.15
# Demo arena
#initial_pose_x:            0.0
#initial_pose_y:            -0.75
# Demo arena 8x14
initial_pose_x:            0.3
initial_pose_y:            -0.9
# ---
initial_pose_a:            0.0
initial_cov_xx:            0.05
initial_cov_yy:            0.05
initial_cov_aa:            0.05
gui_publish_rate:          50.0
laser_max_range:           6.0
laser_max_beams:           30
laser_z_hit:               0.95
laser_z_short:             0.1
laser_z_max:               0.05
laser_z_rand:              0.5
laser_sigma_hit:           0.2
laser_lambda_short:        0.1
laser_likelihood_max_dist: 2.0
laser_model_type:          likelihood_field

odom_model_type:           diff
odom_alpha1:               2.0
odom_alpha2:               2.0
odom_alpha3:               2.0
odom_alpha4:               2.0
odom_frame_id:             odom_4
base_frame_id:             base_link_4
lasamplestep: 0.05


